apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twitch-sub-api
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/DevOps-With-Brian/twitch-sub-ui.git'
    path: argocd
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
