apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitch-sub-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: twitch-sub-api
  replicas: 1
  template:
    metadata:
      labels:
        app: twitch-sub-api
    spec:
      containers:
        - name: twitch-sub-api
          image: devopswithbrian/twitch-sub-api:0.0.1
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: twitch-sub-prd
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twitch-sub-prd
                  key: DB_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: twitch-sub-prd
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: twitch-sub-prd
                  key: SECRET_KEY
            - name: ADMIN_API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: twitch-sub-prd
                  key: ADMIN_API_USERNAME
            - name: ADMIN_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twitch-sub-prd
                  key: ADMIN_API_PASSWORD
            - name: DB_NAME
              value: twitch-sub
            - name: DB_HOST
              value: twitch-sub-db
          ports:
            - containerPort: 8000
              name: twitch-sub-api
